dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest --ignore "./eeve/eeve actions/test_action.py"

deploy:
  provider: pypi
  user: "vMarcelino"
  password: "$secret"